---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"
    role:
      - Writing - Review & Editing

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```


```{r libraries}
library(tidyverse)
library(brms)
library(broom)
library(tidybayes)
```

```{r}
# quick test using brms

# load data
test <- read_csv("data/batch1-test.csv")

pre_test <- test %>% 
  filter(block == "pre")
# sanity check nrow(pre_test)

post_test <- test %>% 
  filter(block == "post")
# sanity check nrow(post_test)

cont_tasks <- ggplot(data = test,
       aes(x=vot, y=resp_t, color = block, group = workerId)) +
  # uncomment to see the actual data points instead of just the mean
  # geom_point(position=position_jitter(h = 0.1), alpha=0.1) +
  geom_line(stat="summary", fun = mean) +
  geom_vline(xintercept = 50, linetype = "dashed", aes( color = "red")) +
  # the line below shows where it seems to actually be ambiguous 
  # geom_vline(xintercept = 40, linetype = "dashed", color = "blue", alpha = 0.5) +
  facet_wrap( . ~ condition) +
  ylab("Proportion of /t/ response") + xlab("VOT (ms)") +
  labs(title = "*Pre- and Post Continuum 'Tent' Responses*", tag = "Figure 1") +
  mdthemes::md_theme_bw() +
  theme(text=element_text(size=11, family = "Times"))
cont_tasks

# quick model
test_model <- brms::brm(resp_t ~ block * condition * vot +
                              (block | workerId), # random intercept for workerId and slope for block 
                              data = test, family = "bernoulli"(link = "logit"))


# intercept model 
int_model <- brm(resp_t ~ 1, data = test, family = binomial(link="logit"))
summary(int_model)
summary(test_model) 

predictors <- as_tibble(int_model) %>% 
  select(b_Intercept) %>% 
  pivot_longer(everything(), names_to = "parameter", values_to = "estimate") %>% 
  ggplot(., aes(x = estimate, y = parameter)) +
    stat_halfeye()

head(predictors)
plot(test_model)
launch_shinystan(test_model)
pp_check(test_model)

```

# Methods

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
